---
categories:
  - prefix: P
    color: "D93F0B"
    labels:
      low: "Priority: Low"
      medium: "Priority: Medium"
      high: "Priority: High"
      critical: "Priority: Critical"
  - prefix: C
    color: "BFD4F2"
    labels:
      bug: "Category: This is a bug."
      enhancement: "Category: An issue or PR with for a proposed enhancement."
      tracking-issue: "Category: A tracking issue for a major feature or change."
  - prefix: E
    color: "94315F"
    labels:
      1-byte: "Effort: Byte (1)"
      2-kilobyte: "Effort: Kilobyte (2)"
      3-megabyte: "Effort: Megabyte (3)"
      4-gigabyte: "Effort: Gigabyte (4)"
      5-terabyte: "Effort: Terabyte (5)"
